### ISSUE TITLE
Fission Charts and Repository Enhancements

### ISSUE THREAD

**Issue by sanketsudake** [fission/fission-charts#47]
We would be closely following  [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts/) as a reference and taking Fission charts repo towards those standards.
 
### Steps

1.  [x] Add detailed README in [fission-charts](https://fission.github.io/fission-charts/) Repo 
2.  [x] Add README in each chart, it is required for Artifact Hub official releases. This is required to improve user exp and make our charts official on Artifact Hub.
3.  [x] Switch default branch to `gh-pages` from `master` in charts repo to serve charts [Reference](https://github.com/prometheus-community/helm-charts/tree/gh-pages)
4.  [ ] Migrated Fission charts source from Fission repository to charts repository, ensure no failures 
5.  [x] Reduction of common code between fission-all and fission-core helm charts and common templates.
6.  [ ] Separate charts release and Fission images/app release. This would require further breakdown going ahead.
7.  [ ] Use [chart-releaser-action](https://github.com/helm/chart-releaser-action) for releasing charts
8. [ ] Use [chart-testing](https://github.com/helm/chart-testing) for testing of charts, add unit tests

### Contributor Notes

- We should ensure there should be clear migration/usage steps mentioned for Fission users.
- All required documentation should be prepared alongside the code.
- We can treat this as a parent issue and link other issues as required.

**Comment by sanketsudake** [comment]
Related https://github.com/fission/fission/issues/2280

**Comment by soharab-ic** [comment]
Refactoring PR is merged. Hence, closing the issue.
